name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # allows manual run

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@hardik.mangukiya.003"
