name: Latest Blog Post Workflow

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # allows manual run

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install rss-parser

      - name: Update README with Medium posts
        run: |
          node - <<'EOF'
          const fs = require('fs');
          const Parser = require('rss-parser');
          const parser = new Parser();

          (async () => {
            try {
              const feedUrl = "https://medium.com/feed/@hardik.mangukiya.003";
              const feed = await parser.parseURL(feedUrl);

              // Take top 5 posts
              const posts = feed.items.slice(0,5).map(item => `- [${item.title}](${item.link})`);

              const readmePath = "README.md";
              let readme = fs.readFileSync(readmePath, "utf8");

              const startTag = "<!-- BLOG-POST-LIST:START -->";
              const endTag = "<!-- BLOG-POST-LIST:END -->";
              const regex = new RegExp(`${startTag}[\\s\\S]*${endTag}`);

              const newContent = `${startTag}\n${posts.join("\n")}\n${endTag}`;
              readme = readme.replace(regex, newContent);

              fs.writeFileSync(readmePath, readme);
              console.log("README.md updated successfully.");
            } catch (error) {
              console.error("Failed to update README:", error.message);
            }
          })();
          EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest Medium posts" || echo "No changes to commit"
          git push
