name: Update README Automatically

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout this repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Optional: Update README content automatically
      - name: Update README
        run: |
          # For example, append timestamp to README
          echo -e "\nLast updated: $(date)" >> README.md

      # Step 3: Commit & push changes
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automated update to README" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
